In an attempt to clear up "view more" Challenge
FreeCodeCampChina/freecodecamp.cn pull request #177
Opened 2017-03-02 08:38 UTC by wudifeixue

- [ ] LGTM
- [ ] LGTM

In this PR:
* Add to comments guide the student for more clarity on the question. (non-breaking changes)
* Try to prevent these issues from happening again: #22 #28 #48 #50 #103

2017-03-02 23:03 UTC, S1ngS1ng requested changes

2017-03-02 23:03 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/html5-and-css.json
> +        "<!-- 只更改上面的内容 -->",
参考下[这里的描述](https://github.com/wudifeixue/freecodecamp.cn/blob/6add2c083fc30f789a38aecacc0011e8e826b6d4/seed/challenges/01-front-end-development-certification/jquery.json#L22)，
改成 `<!-- 只更改这条注释以下的代码。 -->` 和 `<!-- 只更改这条注释以上的代码。 -->` 如何？

2017-03-02 23:15 UTC, wudifeixue commented on seed/challenges/01-front-end-development-certification/html5-and-css.json
> +        "<!-- 只更改上面的内容 -->",
可以，确实应该统一下

2017-03-04 02:22 UTC, wudifeixue commented on seed/challenges/01-front-end-development-certification/html5-and-css.json
> +        "<!-- 只更改上面的内容 -->",
改完了

2017-03-04 06:00 UTC, S1ngS1ng approved these changes

2017-03-04 06:00 UTC, S1ngS1ng commented
LGTM

2017-03-04 06:06 UTC, merged