Update tranlation of comment in basic-javascript
FreeCodeCampChina/freecodecamp.cn pull request #253
Opened 2017-04-19 21:13 UTC by S1ngS1ng

## In this PR:
- Update translation of comments

2017-04-20 06:12 UTC, wudifeixue commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
> +        "// 定义 myFunction",
哇你给的提示好多

2017-04-20 06:19 UTC, wudifeixue requested changes
看看如果还有哪里有 Change Me 也一起改了吧，多谢~

2017-04-20 06:19 UTC, wudifeixue commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
>          "  return \"Change Me!\";",
有好几处 Change Me! 这个我觉得很有必要也翻译一下。今晚QQ群又遇见[Counting Card](https://github.com/FreeCodeCampChina/freecodecamp.cn/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20counting)老问题觉得翻译了return Change Me肯定可以有所帮助。

2017-04-20 07:21 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
>          "  return \"Change Me!\";",
好的

2017-04-20 07:23 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
> +        "// 定义 myFunction",
@wudifeixue 其实这些就是翻译啦。。没啥特别的= =

2017-04-22 16:16 UTC, wudifeixue approved these changes

2017-04-22 16:16 UTC, wudifeixue commented
okay

2017-04-22 16:16 UTC, merged