Update challenge description of Word Blanks
FreeCodeCampChina/freecodecamp.cn pull request #277
Opened 2017-05-07 03:10 UTC by S1ngS1ng

## In this PR
- Update challenge description of Word Blanks
- As mentioned in #276

2017-05-07 17:07 UTC, wudifeixue requested changes
We need a better example.

2017-05-07 17:07 UTC, wudifeixue commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
> +        "此外，为了句子通顺，你可以在包含所有传入单词的前提下自己添加一些其他单词。对于上面的例子，函数返回值为 <code>\"That big brown dog surprisingly run just quickly\"</code> 也是没问题的"
你不觉得 That big brown dog surprisingly run just quickly 念出来很不通顺么..一下子三个副词。而且副词是用来帮助动词的，应该在后面吧。
一定想的话，感觉 That big brown dog run surprisingly quick. 稍微合适些。但是依然觉得有点没有意义。

2017-05-08 04:15 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
> +        "此外，为了句子通顺，你可以在包含所有传入单词的前提下自己添加一些其他单词。对于上面的例子，函数返回值为 <code>\"That big brown dog surprisingly run just quickly\"</code> 也是没问题的"
@wudifeixue 还是加上吧。至少，给出正确的写法😂
判断那里只是检测了是否包含传入的字符串

2017-05-09 04:40 UTC, S1ngS1ng reviewed
Pending

2017-05-09 04:41 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
> +        "此外，为了句子通顺，你可以在包含所有传入单词的前提下自己添加一些其他单词。对于上面的例子，函数返回值为 <code>\"That big brown dog just run quickly\"</code> 也是没问题的"
@wudifeixue 你的那种写法确实读起来会更通顺一些。但有一个问题，传入的是 `quickly` 而不是 `quick`。所以你看看，这样改如何？

2017-05-09 12:43 UTC, wudifeixue commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
> +        "此外，为了句子通顺，你可以在包含所有传入单词的前提下自己添加一些其他单词。对于上面的例子，函数返回值为 <code>\"That big brown dog just run quickly\"</code> 也是没问题的"
很棒，这次通顺很多👌

2017-05-09 12:43 UTC, merged