Enhance and fix translation on JSON api and AJAX
FreeCodeCampChina/freecodecamp.cn pull request #353
Opened 2017-08-01 05:53 UTC by wudifeixue

In this PR:

Fix Issue: #346 

Enhance and fix translation on challenge JSON api and AJAX.

2017-08-01 18:04 UTC, S1ngS1ng requested changes
Let me know in case of any further questions.

2017-08-01 18:04 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/json-apis-and-ajax.json
> +        "assert(code.match(/filter/gi), 'message: 你应该使用 .filter 这个方法。');"
Might wanna consider onsider `<code>.filter</code>`?

2017-08-01 18:04 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/json-apis-and-ajax.json
> +        "在浏览器中还有一个很棒的功能就是我们还可以通过<code>navigator</code>来获得我们当前所在的地理位置<code>geolocation</code>。",
还有一件很棒的事情，我们可以获取用户的当前位置。每个浏览器都有自带的 <code>Navigator</code> 接口供我们调用。

2017-08-01 20:04 UTC, wudifeixue commented on seed/challenges/01-front-end-development-certification/json-apis-and-ajax.json
> +        "在浏览器中还有一个很棒的功能就是我们还可以通过<code>navigator</code>来获得我们当前所在的地理位置<code>geolocation</code>。",
昨晚我就想了有点怪，不过感觉怎么感觉还是很绕口233 不过再改改吧。

2017-08-02 18:42 UTC, S1ngS1ng approved these changes
LGTM :100:

2017-08-02 18:42 UTC, merged