Change required description on Safari
FreeCodeCampChina/freecodecamp.cn pull request #512
Opened 2018-05-17 16:41 UTC by wudifeixue

In this PR:

Fixes #447

2018-05-18 05:15 UTC, S1ngS1ng requested changes
Typo :P

2018-05-18 05:17 UTC, S1ngS1ng requested changes

2018-05-18 05:17 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/html5-and-css.json
> +        "注意：<code>required</code>属性在Safari浏览器10.1以下不起作用（2017年3月27以前)，请更更新Safari或者使用其他浏览器来学习，推荐使用Chrome。"
"请更更新" => "请更新"

2018-05-18 05:18 UTC, S1ngS1ng commented on seed/challenges/01-front-end-development-certification/html5-and-css.json
> +        "注意：<code>required</code>属性在Safari浏览器10.1以下不起作用（2017年3月27以前)，请更更新Safari或者使用其他浏览器来学习，推荐使用Chrome。"
Also, please unify the symbols (parenthesis here) to EITHER full-width OR half-width. Mix & match won't be a good idea 😂

2018-05-18 15:06 UTC, wudifeixue commented on seed/challenges/01-front-end-development-certification/html5-and-css.json
> +        "注意：<code>required</code>属性在Safari浏览器10.1以下不起作用（2017年3月27以前)，请更更新Safari或者使用其他浏览器来学习，推荐使用Chrome。"
哈哈好尴尬呀居然打错了字，那我括号也改一改好了

2018-05-28 18:23 UTC, wudifeixue commented
Updated now

2018-05-29 16:20 UTC, S1ngS1ng approved these changes

2018-05-29 16:21 UTC, merged