Juzhiyuan
FreeCodeCampChina/freecodecamp.cn pull request #519
Opened 2018-05-23 09:22 UTC by juzhiyuan

## FreeCodeCamp Pull Request template
Please, go through these steps before you submit a PR.

1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:

  2.1. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.

  2.2. You have a descriptive commit message with a short title (first line).

  2.3. You have only one commit (if not, [squash](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/git-rebase#squashing-multiple-commits-into-one) them into one commit).

  2.4. `npm test` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).

3. **After** these steps, you're ready to open a pull request.

  3.1. Your pull request MUST NOT target the `master` branch on FreeCodeCamp's repository. You probably want to target `staging` instead.

  3.2. Give a descriptive title to your PR.

  3.3. Provide a description of your changes.

  3.4. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

2018-05-24 05:53 UTC, S1ngS1ng commented
![image](https://user-images.githubusercontent.com/13592559/40466807-17ac8532-5edc-11e8-9ebd-739fce5e3808.png)

@wudifeixue Time to remove this challenge 🤦‍♂️

2018-05-24 05:56 UTC, juzhiyuan commented
I just modified two files: index.html & index.css

2018-05-24 06:21 UTC, S1ngS1ng commented
@juzhiyuan 我这里获取不到你的改动。你有没有 `push` 呢？

2018-05-24 06:24 UTC, juzhiyuan commented
@S1ngS1ng 有的，并且提交PR了。但是我没有点击Merge，这个事情应该由专人负责的吧。

2018-05-24 06:25 UTC, juzhiyuan commented
![image](https://user-images.githubusercontent.com/2106987/40467912-3c9026ce-5f5e-11e8-8422-dd68e701b4f2.png)

2018-05-24 06:27 UTC, S1ngS1ng requested changes
先把最后那行删了吧，别的问题不大~

2018-05-24 06:27 UTC, S1ngS1ng commented on public/index.html
> +              <img src="https://staticfile.shaoyaoju.org/20180523/地图2.png" alt="">
这几个图，后续会换成图标 + 文字的形式吧？现在看着很模糊。
![image](https://user-images.githubusercontent.com/13592559/40467838-3ad8e272-5ee0-11e8-88df-3fdf187510fb.png)

2018-05-24 06:27 UTC, S1ngS1ng commented on public/index.html
> +No newline at end of file
感觉这一行像是 lint tool 加上的。删掉换成空行就好了

2018-05-24 06:27 UTC, S1ngS1ng commented on public/index.html
> +    <header>顶部菜单栏</header>
这个，还有 “底部区域”，“课程大纲” 那些都是暂时放在这儿占位的吧？

2018-05-24 06:27 UTC, S1ngS1ng commented on public/index.html
> +          <div class="swiper-slide">
移动端，怕是不太友好😂
![image](https://user-images.githubusercontent.com/13592559/40467969-b781b088-5ee0-11e8-8cc7-4822c9219e5f.png)
咱们还需要处理这个么？

2018-05-24 06:29 UTC, juzhiyuan commented
@S1ngS1ng 航哥说不用管移动端；最后一行是 @chj-damon 写框架的时候留在上面的；图像会更换掉的；课程大纲、底部区域等由其他人负责。

2018-05-24 06:32 UTC, S1ngS1ng commented
@juzhiyuan 好的 👍

2018-05-24 06:33 UTC, S1ngS1ng approved these changes

2018-05-24 11:47 UTC, merged

2018-05-28 18:29 UTC, wudifeixue commented
@S1ngS1ng I think we should just remove the Friendly Date Challenge, first, it's not friendly at all, second, the English one has already removed it.